<a href="https://colab.research.google.com/github/SerginhoTanaka/TrabalhoTania/blob/main/Multiplica%C3%A7%C3%A3o_de_Matrizes_T%C3%A2nia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np
a = np.array([[3,1, 3], [6, 5, 5]], np.int32)
b = np.array([[100,50],[50,100],[50,50]],np.int32) 
print("Matriz de botões por camisa:")
print(b)
print("Matriz de camisa por mês:")
print(a)
print("Total de botões pelos meses:")
c = a.dot(b)
print(c)
soma = 0
for i in range(2):
  for j in range(2):
    soma = soma + c[i][j]

print("Total de botões", soma)





Matriz de botões por camisa:
[[100  50]
 [ 50 100]
 [ 50  50]]
Matriz de camisa por mês:
[[3 1 3]
 [6 5 5]]
Total de botões pelos meses:
[[ 500  400]
 [1100 1050]]
3050
